### ISSUE TITLE
Graphql subscriptions

### ISSUE THREAD

**Issue by kodeine** [hardyscc/nestjs-cqrs-starter#378]
Really like the efforts you've put into this. 

Does this lib support graphql subscriptions? On nestjs docs it says federation does not support subscriptions.

Any ideas how can we achieve subscriptions?

**Comment by hardyscc** [comment]
@kodeine  Although this feature is on the [Apollo 3 roadmap](https://github.com/apollographql/apollo-server/issues/2360), however this has been a long wait (over a year) and the progress is very slow. In the meantime you can only use socket.io directly.

**Comment by kodeine** [comment]
@hardyscc so you mind adding an example please? I'm new to cqrs and now socket.io

**Comment by hardyscc** [comment]
@kodeine sorry that I didn't use it before too, however you can follow this to get start https://docs.nestjs.com/websockets/gateways

**Comment by kodeine** [comment]
@hardyscc since we are already catching events. I wanted to ask how would you approach this.

Should I make another app that catches all events and pass them to ws? Like an event proxy to ws?

Or where should I setup a proxy to emit events to ws? Your input is really appreciated

**Comment by hardyscc** [comment]
@kodeine I think you can subscribe to the event store (directly under the gateway), and emit the event through WebSocketGateway like that... (I am not very sure this will work or not)

```ts
@WebSocketGateway()
export class EventsGateway {
  constructor(
    private readonly event$: EventBus
  ) {}

  @SubscribeMessage('events')
  subscribeEvent(@MessageBody() data: any): Observable<WsResponse<any>> {
    return events$.pipe(
      ofType(XxxxEvent),
      map((event) => ({ event: 'events', data: event }),
    )
  }
}
```

**Comment by kodeine** [comment]
I have a question, so if i am working on auth app. It needs user service. How would i approach the service since we are dealing with microservices. 

I know i can just call user service from auth service but again doesn't feel right. How would you approach it?

**Comment by hardyscc** [comment]
There is a more complete example project which include authentication under https://github.com/juicycleff/ultimate-backend
please take a look first to see if you have any inspiration.
