### ISSUE TITLE
How to replay events?

### ISSUE THREAD

**Issue by SkyaTura** [hardyscc/nestjs-cqrs-starter#521]
Hi, first of all, nice repository. I've been studying Event Sourcing in the last couple weeks and this is one of the finest example I've seen so far.

However, I'm wondering, is it possible to replay events?

Let's say that I change the projection structure and want to update my states to fit it, how should I proceed?

**Comment by hardyscc** [comment]
Im sorry to told u that u cannot not have a separate projection structure, as you can see in this example the database commit and event firing is combined.. for production grade CQRS & Event Sourcing framework, Axon Framework seems to be the only choice at this moment.

**Comment by hardyscc** [comment]
@SkyaTura You can create a new persistent subscription let say xxxxx, all the events will be fire again!

```ts
    EventStoreModule.registerFeature({
      type: 'event-store',
      featureStreamName: '$svc-xxxxx',
      subscriptions: [
        {
          type: EventStoreSubscriptionType.Persistent,
          stream: '$svc-user',
          persistentSubscriptionName: 'xxxxx',
        },
        {
          type: EventStoreSubscriptionType.Persistent,
          stream: '$svc-account',
          persistentSubscriptionName: 'xxxxx',
        },
      ],
      ...
    }),
  ],
```
